# Generated by Django 3.1.7 on 2021-09-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210924_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
