# Generated by Django 3.1.7 on 2021-10-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20211009_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='buy_quantity',
            new_name='save_quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='seller',
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
