# Generated by Django 3.1.7 on 2021-10-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_order_shippingprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='shippingprice',
            field=models.FloatField(default=100),
        ),
    ]
