# Generated by Django 3.1.7 on 2021-10-12 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='seller',
        ),
    ]
