# Generated by Django 3.1.7 on 2021-10-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20211013_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='user',
        ),
    ]
